primate/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("prime.urls")),
    path('admin/', admin.site.urls),
]

prime/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile, notification

app_name = "prime"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("notification", notification, name="notification"),
]

prime/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Prime(models.Model):
    user = models.ForeignKey(User, 
                            related_name="primes", 
                            on_delete=models.DO_NOTHING)

    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:100]}..."
        )

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    educational_stats = models.CharField(max_length=100, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=80, blank=True)
    state = models.CharField(max_length=50, blank=True)
    local_govt = models.CharField(max_length=50, blank=True)
    nationality = models.CharField(max_length=55, blank=True)
    gender = models.CharField(max_length=25, blank=True)
    email = models.EmailField(null=True, max_length=100, blank=True)
    phone_number = models.IntegerField(blank=True, null=True)
    first_name = models.CharField(max_length=55, blank=True)
    other_name = models.CharField(max_length=55, blank=True)
    last_name = models.CharField(max_length=55, blank=True)
    profesion = models.CharField(max_length=100, blank=True)



    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)



@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

prime/forms.py
from django import forms
from .models import Prime

class PrimeForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "What's on your mind...",
                "class": "textarea is-success is-small",
            }
        ),
        label="",
    )

    class Meta:
        model = Prime
        exclude = ("user", )

prime/views.py
from django.shortcuts import render, redirect
from .forms import PrimeForm
from users.models import Profile
from prime.models import Prime


# Create your views here.
def dashboard(request):
    form = PrimeForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            prime = form.save(commit=False)
            prime.user = request.user
            prime.save()
            return redirect("prime:dashboard")
    followed_primes = Prime.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")

    return render(
        request,
        "prime/dashboard.html",
        {"form": form, "primes": followed_primes},
    )

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "prime/profile_list.html", {"profiles": profiles})


def profile(request, pk):

    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "prime/profile.html", {"profile": profile})

def notification(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "prime/notification.html", {"profiles": profiles})

users/views.py
from django.shortcuts import render

# Create your views here.

prime/templates/base.html
{% load bootstrap4 %}
<!doctype html>
    <html lang="en">
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
        <!-- Include the Bulma CSS framework for styling -->
        <link rel="stylesheet"  href=
        "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
            <script src="https://use.fontawesome.com/releases/v5.1.0/js/all.js">
        </script>
        <title>Teaserfunapp</title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
</head>

<body>
    
<header>
  <section>
  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-primary mb-4 border">
    <h3 style="color: rgb(1, 1, 8);">Taserfunapp</h3>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarCollapse" aria-controls="navbarCollapse"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="#">
        </a></li>
      </ul>
          {% if user.is_authenticated %}
              <ul>
                <li>
                  <a href="{% url 'prime:dashboard' %}">
                    <i class="fa fa-home fa-fw" style="font-size:35px;color:greenyellow"></i>
                  </a>
                </li>
              </ul>
              
              <ul>
                  <li>
                      <a href="{% url 'prime:notification' %}">
                        <i class="fa fa-bell fa-fw" style="font-size:35px;color:greenyellow"></i>
                      </a>
                  </li>
              </ul>
              
              <ul class="navbar-nav ml-auto "> 
                <li class="nav-item">
                <img src="ikechi.jpg">
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'prime:profile' request.user.profile.id %}">{{ user.profile.first_name }}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            {% endif %}

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                <span class="navbar-text"}> <p>Hello, {{ user.profile.first_name }}
                  {{ user.profile.other_name }}
                  {{ user.profile.last_name }}.
                  </p>
                </span>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Sign out</a>
                </li>
                {% else %}
                <li class="nav-item">
                <a class="nav-link" href="#">Sign up</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Sign in</a></li>
                {% endif %}
                </ul>
                </div>
  </nav>
  </section>
</header>
<hr>
<hr>
<hr>
            



                {% block content %}
                
                {% endblock content %}
               

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

</body>
</html>

prime/templates/prime/dashboard.html
{% extends 'base.html' %}

{% block content %}

<br>
<br>
<br>


<div class="columns is-centered">
  <div class="column is-one-third">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
                type="submit">Post
        </button>
    </form>
  </div>
</div>
<hr>
<hr>
{% for prime in primes %}
<div class="tile is-parent">
  <div class="tile is-child box notification 
               has-background-dark has-text-success">
<div class="columns is-centered">
    <div class="column is-half">
        <div class="block">
            <div class="card">
                <div class="card-content">
                    <div class="media">
                      <div class="media-left">
                        <figure class="image is-59x48">
                          <img src="https://bulma.io/images/placeholders/96x96.png"
                               alt="Placeholder image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">
                          {{ users.profile.user.first_name }}
                        </p>
                        <p class="subtitle is-6">
                          @{{ user.username|lower }}
                        </p>
                    </div>
            </div>
        <hr>
        <p>
            {{prime.body}}
        </p>
        <p class="is-small has-text-grey-light">
            ({{ prime.created_at }}) ( by {{ prime.user.username }})
        </p>
        <hr>
        <hr>
        <hr>
        <hr>
        <hr>
        <hr>
        <hr>
       
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
{% endfor %}

{% endblock content %}

prime/templates/prime/notification.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

<div class="columns is-centered">
    <div class="column is-half">
        <div class="block">
            <div class="card">
                <div class="card-content">

                        <h1 style="color: blue;">Page Currently under  construction</h1>
                        <hr>
                            <p style="color: rgb(41, 6, 240);">We sincerely appologize for any incovinience 
                                this might have caused you..
                                Our team is currently working 
                        <hr>
                            </p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

prime/templates/prime/profile.html
{% extends 'base.html' %}

{% block content %}

<br>
<br>
<br>

<div class="container">

    <div class="tile is-ancestor">
        <div class="tile is-4 is-vertical is-parent">
            <div class="tile is-child box notification 
                          has-background-dark has-text-success">

                          <p class="title">Bio</p>
                          <div class="box">
                            <article class="media">
                              <div class="media-left">
                                  {% if profile.image %}
                                <figure>
                                  <img src="{{ profile.image.url }}" width="80">
                                </figure>
                                {% endif %}
                              </div>
                              <div class="media-content">
                                <div class="content">
                                  <p>
                                    {{ profile.bio|slice:100 }}
                                    <a class="read-more-btn" href="{{content.absolute_url}}">Read More</a>
                                  </p>
                                </div>
                              </div>
                            </article>
                          </div>
                          <hr>
          
                <p class="title">Personal Info</p>
                <hr>
                <p>
                Email: <br>{{profile.email}}
                 <hr>
                Country: <br>{{profile.nationality}}
                 <hr>
                Location: <br>{{ profile.location }}
                  <hr>
                Contact: <br>{{profile.phone_number}}
                  <hr>
                Date of Birth: <br>{{profile.birth_date}}
                 <hr>
                Education: <br>{{profile.educational_stats}}
                  <hr>
                Profession: <br>{{profile.profesion}}
                   <hr>
                State of Origin: <br>{{profile.state}}
                    <hr>
                Local Govt.: <br>{{profile.local_govt}}
                    <hr>
                Gender: <br>{{profile.gender}}
                    <hr>
                </p>
                <hr>
              </div>

              
            <div class="tile is-child box notification  
                         has-background-dark has-text-success">
                         <p class="title">Contacts</p> <hr>
                         <div class="block">
                          <h3 class="title is-4">
                              {{profile.user.username}} follows:<hr>
                          </h3>
                          <div class="content">
                              <ul>
                              {% for following in profile.follows.all %}
                              <li>
                                
                                      <a href="{% url 'prime:profile' following.id %}">
                                          {{ following }}
                                      </a>
                                  </li>
                                  <hr>
                              {% endfor %}
                              </ul>
                          </div>
                         
                      </div>
                  
                      <div class="block">
                          <h3 class="title is-4">
                              {{profile.user.username}} is followed by:<hr>
                          </h3>
                          <div class="content">
                              <ul>
                              {% for follower in profile.followed_by.all %}
                                  <li>
                                      <a href="{% url 'prime:profile' follower.id %}">
                                          {{ follower }}
                                      </a>
                                  </li>
                                  <hr>
                              {% endfor %}
                              </ul>
                          </div>
                      </div>


            </div>
        </div>

        <div class="tile is-parent">
            <div class="tile is-child box notification 
                         has-background-dark has-text-success">
                <div class="column">
                    <div class="media">
                        <div class="media-left">
                          <figure>
                            <img src="#" border-radius="%", width="250">
                          </figure>
                        </div>
                    <div class="media-content">
                    <p class="title is-4">
                    <div class="block">
                    <h1 class="title is-6">
                        {{profile.first_name|upper}}
                        {{profile.other_name|upper}}
                        {{profile.last_name|upper}}
                        <br><br>
                        (@{{profile.user.username|lower}})
                    </h1>
                    </div>
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="buttons has-addons">
                        {% if profile in user.profile.follows.all %}
                            <button class="button is-success is-static">Follow</button>
                            <button class="button is-danger" name="follow" value="unfollow">
                                Unfollow
                            </button>
                        {% else %}
                            <button class="button is-success" name="follow" value="follow">
                                Follow
                            </button>
                            <button class="button is-danger is-static">Unfollow</button>
                        {% endif %}

                        </div>
                    </form>
                    </div> 
                    </div>

            <div class="content">
                <hr>
                {% for prime in profile.user.primes.all %}
                <hr>
                    <div class="box">
                        <hr>
                        {{ prime.body }}
                <hr>
                        <span class="is-small has-text-grey-light">
                            ({{ prime.created_at }})
                        </span>
                    </div>
                {% endfor %}
            </div>


            {% endblock content %}

prime/templates/prime/profile_list.html
{% extends 'base.html' %}

{% block content %}
<hr>
<hr>
<hr>

{% for profile in profiles %}

<div class="columns is-centered">
<div class="column is-one-third">



    <div class="block">
      <div class="card">
        <a href="{% url 'prime:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-59x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
                <hr>
                <hr>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
</div>
</div>
</div>
{% endfor %}

</div>

{% endblock content %}